[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
authors = [
    {name = "Northwestern University", email = "DL_FSM_GDS@e.northwestern.edu"}
]
classifiers = [
    "Environment :: Web Environment",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Programming Language :: Python :: 3",
]
dependencies = [
    "invenio-subjects-mesh-common>=0.3.0,<2.0"
]
description = "MeSH subject terms without qualifiers"
keywords = ["invenio", "inveniordm", "subjects", "MeSH"]
license = "MIT"
name = "invenio-subjects-mesh-lite"
readme = "README.md"
requires-python = ">=3.11"
urls = {Repository = "https://github.com/galterlibrary/invenio-subjects-mesh-lite"}
version = "2026.1.27.1"

[project.optional-dependencies]
dev = [
    "invenio-subjects-mesh-common[dev]>=0.3.0,<2.0",
    "invenio-search[opensearch2]>=3.1.0,<4.0.0",  # Needs to be specified separately as it's normally up to the instance
    "invoke>=3.0,<4.0",
    "pyyaml>=5.4.1",
    "pytest-invenio>=4.0.1,<5.0.0",
    # pytest-invenio includes pytest & co and docker-services-cli
]

dev_pre = [
    "invenio-subjects-mesh-common[dev_pre]>=0.3.0,<2.0",
    "invenio-search[opensearch2]>=3.1.0,<4.0.0",
    "invoke>=3.0,<4.0",
    "pyyaml>=5.4.1",
    "pytest-invenio>=4.0.1,<5.0.0",
]

[project.entry-points."invenio_rdm_records.fixtures"]
invenio_subjects_mesh_lite = "invenio_subjects_mesh_lite.vocabularies"

[tool.hatch.build.targets.sdist]
include = [
  "invenio_subjects_mesh_lite",
]

[tool.hatch.build.targets.wheel]
packages = [
  "invenio_subjects_mesh_lite",
]

[tool.pydocstyle]
add_ignore = ["D401", "D403"]

[tool.pytest.ini_options]
minversion = "6.0"
# ATTN: Remove the cov options when using breakpoint() since it interferes
addopts = '--isort --pydocstyle --pycodestyle --doctest-glob="*.rst" --doctest-modules --cov=invenio_subjects_mesh_lite --cov-report=term-missing'
testpaths = ["tests", "invenio_subjects_mesh_lite"]

[tool.uv]
# this is needed so that `uv run --extra dev_pre` doesn't
# raise an incompatibility error according to uv.
# See https://docs.astral.sh/uv/concepts/projects/config/#conflicting-dependencies
conflicts = [
    [
      { extra = "dev" },
      { extra = "dev_pre" },
    ],
]
